### ISSUE TITLE
Wallet Error - Messaging identity address is not found in wallet

### ISSUE THREAD

**Issue by yatesdr** [bitcoinz-pod/bitcoinz-wallet#1]
Every few minutes, a window pops up saying:

"The messaging identity send/receive address: <zcJLUX ...> is not found in wallet.dat.  The reason may be that after a mesaging identity was created the wallet.dat was changed or the BTCZ node configuration was changed (e.g. mainnet -> testnet).  If such a change was made, the messaging identity can no longer be used.  To avoid this error message, you may rename the directory C:\...\messaging until the configuration or wallet.dat is restored!   Directory may only be renamed when the wallet is stopped!

It appears that this release is also using the Zencash wallet's own identity, which is leading to this error.   I do have Zencash and BTCZ wallets both installed.

Suggested fix:  Change the messaging folder directory from Appdata\Local\ZENCashSwingWalletUI\messaging to Appdata\Local\BTCZSwingWalletUI\messaging, or in fact update the messaging portion of this release to save the wallet in some directory separate from the ZEN wallet.

**Comment by bitcoinz-pod** [comment]
Thanks, directory has been changed.
