### ISSUE TITLE
Debian package fails

### ISSUE THREAD

**Issue by cryptorex** [bitcoinz-pod/bitcoinz-wallet#10]
Debian package fails:

ubuntu@ubuntu1604:~$ sudo dpkg -i bitcoinz-wallet_1.1.0.deb 
Selecting previously unselected package bitcoinz-wallet.
(Reading database ... 270283 files and directories currently installed.)
Preparing to unpack bitcoinz-wallet_1.1.0.deb ...
Unpacking bitcoinz-wallet (1.1.0) ...
dpkg: dependency problems prevent configuration of bitcoinz-wallet:
 bitcoinz-wallet depends on bitcoinz; however:
  Package bitcoinz is not installed.

dpkg: error processing package bitcoinz-wallet (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 bitcoinz-wallet

**Comment by bmatthewshea** [comment]
Just what it says - your are missing DEB dependencies:
`bitcoinz-wallet depends on bitcoinz; however:
Package bitcoinz is not installed.`

So you probably need this:
https://github.com/bitcoinz-pod/bitcoinz/releases (bitcoin deb or compile it)

DEB bitcoinz wallet info:


`dpkg-deb -I bitcoinz-wallet_1.1.0.deb`

 new debian package, version 2.0.
 size 335522 bytes: control archive=426 bytes.
      66 bytes,     2 lines      bitcoinz-wallet      #!/bin/bash
     196 bytes,     9 lines      control
     139 bytes,     2 lines      md5sums
 Package: bitcoinz-wallet
 Version: 1.1.0
 Section: misc
 Priority: low
 Architecture: all
 **Depends: default-jdk, bitcoinz**
 Installed-Size: 348
 Maintainer: ivan@vaklinov.com
 Description: BitcoinZ Wallet

**Comment by bitcoinz-pod** [comment]
You just need to install bitcoinz package dependency from releases page.
