### ISSUE TITLE
Can't select destination folder for blockchain

### ISSUE THREAD

**Issue by Shadybliss** [bitcoinz-pod/bitcoinz-wallet#11]
This is a must have for me considering just my windows is on the Main ssd and there is not a lot of room on there. 

I have 2 other ssds and they are 2tb each. 

Please add an options to select destination folder when downloading/syncing blockchain.

**Comment by bitcoinz-pod** [comment]
good point. For now you can use symlink
https://github.com/bitcoinz-pod/bitcoinz-wallet/issues/4
