### ISSUE TITLE
Win32.Trojan.WisdomEyes.16070401.950

### ISSUE THREAD

**Issue by shagijs** [bitcoinz-pod/bitcoinz-wallet#14]
BitcoinZ Wallet 1.1.0_1.2

After i unrar - bitcoinz-windows-wallet_1.1.0_1.2_seeders_win64 and check file  - bitcoinz-wallet in https://www.virustotal.com Baidu throws out **Win32.Trojan.WisdomEyes.16070401.9500.9527**
As well my antivirus delete that file if I tray to run wallet with virus alert!

**Comment by bitcoinz-pod** [comment]
We removed exe file to get rid of false positives virus scanner issues
