### ISSUE TITLE
Coins lost

### ISSUE THREAD

**Issue by Lexi27** [bitcoinz-pod/bitcoinz-wallet#16]
I got a new phone and put in the recovery phrase and there was a red error saying that it could not recreate it the wallet on the new phone. I checked everything, the phrase was correct, I tried recreated it many times and it would not work. So I went to my old phone and clicked on 'Personal wallet' and it said This wallet is not registered ... tap to recreate. So I taped it and all the money was gone. I am now able to recreate the wallet on the new phone but both phones say that I have 0 BTZ in them. How do I get the fund back?

**Comment by Lexi27** [comment]
Anyone?

**Comment by Lexi27** [comment]
Anyone here?

**Comment by JimTriangle** [comment]
Hello, join the slack of bitcoinz i think you will quickly get answer to your problem.

You can also try solutions listed on https://bitcoinzguiding.ovh/wallet.html

**Comment by bitcoinz-pod** [comment]
Please ask questions about MyBitcoinZ in slack. This is different wallet.
