### ISSUE TITLE
Do not come btcz on MyBitcoinZ wallet

### ISSUE THREAD

**Issue by mainM00007** [bitcoinz-pod/bitcoinz-wallet#17]
Good afternoon. Help, sent 2600 btcz to your address MyBitcoinZ wallet, funds do not come.
https://bitcoinz.ph/tx/77a7420f7012d4816c1cd9542da84089f87d54971e3e586b464d5a8fbd692a97

Bad work wallet((

If I send btcz to the stock exchange, then everything goes away

**Comment by bitcoinz-pod** [comment]
Please ask questions about MyBitcoinZ in slack. This is different wallet.
