### ISSUE TITLE
Transaction not received on my MybitcoinZ wallet 

### ISSUE THREAD

**Issue by Visents** [bitcoinz-pod/bitcoinz-wallet#18]
Hello, I need help. I sent a transaction of 30000 btcz of tradesathosi yesterday and I I have not received the coins in my MyBitcoinZ wallet.
The transaction number is:
494d716555b413b515ac8ea9c0aadb0ff15fd73db6886369ef094bbf921a8162
Thank you

**Comment by kovacbb** [comment]
did you wait for blockchain update?
![image](https://user-images.githubusercontent.com/1457665/33965816-9879252e-e05d-11e7-8b30-100b3c25af48.png)

**Comment by cryptorex** [comment]
Please try:

Settings -> Select wallet -> More Options -> Addresses -> Scan Addresses for Funds.

**Comment by bitcoinz-pod** [comment]
In case of MybitcoinZ issues please ask folks in slack
