### ISSUE TITLE
Transfer To Private Address/Wallet Encryption

### ISSUE THREAD

**Issue by Radar166** [bitcoinz-pod/bitcoinz-wallet#19]
When Attempting to transfer coins to a private address this error occurs. The sending progress starts and the progress bar is shown.  But the transfer fails in the middle of the process.   Please let me know if I can provide more info etc. 
Wallets will not allow encryption at this point either. 

"An error occurred when sending cash.  Error message is: general exception: std::bad_alloc

please ensure sending parameters are correct.  You may try again later."

**Comment by bitcoinz-pod** [comment]
You need to have 4GB of RAM
Encryption is not supported
