### ISSUE TITLE
can't encrypt my wallet

### ISSUE THREAD

**Issue by alyfree** [bitcoinz-pod/bitcoinz-wallet#2]
i download and install bitcoinz-wallet than i want to make password but i can't do it

the encrypt is not active as the picture ...i try to press Ctrl+E no thing happen ..
please help to encrypt the wallet
![zz](https://user-images.githubusercontent.com/6421928/31088296-6b8be786-a7a0-11e7-8c7a-8ac6b6167e93.jpg)

**Comment by bitcoinz-pod** [comment]
zcash devs had problem with encryption. Currently it is disabled in zcash and all zcash forks.
