### ISSUE TITLE
ZCL Windows Wallet 1.1.0.3 - Blockchain not synchronized

### ISSUE THREAD

**Issue by dhtrinh** [bitcoinz-pod/bitcoinz-wallet#21]
Hello, 

My ZCL Windows Wallet 1.1.0.3 has the blockchain synchronized at only 0.02% and no connexion. What should I do?

I added following line into zclassic.conf but the wallet stays at the same.
addnode=136.33.111.57
addnode=52.207.253.9
addnode=34.211.79.94
addnode=148.251.6.58
addnode=38.99.163.72
addnode=62.12.7.151
addnode=52.50.226.122
addnode=46.101.249.50
addnode=btzseed.blockhub.info
addnode=dnsseed.kemperink.org
addnode=seeder.nomadteam.net
addnode=btcz.webrats.com
addnode=btcz.es
addnode=seed.btcz.life
addnode=btcz.vnminers.com
addnode=ajnnljf6ybwyazfw.onion

Thanks for your help.

**Comment by sdustmcore** [comment]
you can try my version:
https://pan.baidu.com/s/1o7AZhuq

**Comment by bitcoinz-pod** [comment]
closing, please use latest ZCL wallets from official website
