### ISSUE TITLE
ZCL Windows Wallet 1.1.0.3 - Blockchain not synchronized 99.99%

### ISSUE THREAD

**Issue by MojoNation** [bitcoinz-pod/bitcoinz-wallet#22]
I saw it sync only once early on to 100%. 

It's sitting on 99.99% I have 7 connections.
Wallet is always open.
I see the data stream working fine.
I have restarted few times.
Running for days.

Wallet still does not show a balance. I have been paid coins many times as per pool summary. ~100 btcz.

Logo was stated as being updated, still shows as ZCL.
Folders also point to Zclassic etc. I've seen instructions referring to \bitcoinz. (Unsure if this matters.)

Resident varies from ~98 to 460MB over time. (Unsure if this matters)

EDIT:
It is now finally on 100%
Perhaps this is a type of rounding issue ?

It still shows NO coins. Is this related to the wallet type ? Is this a bitcoinz wallet or Zcash wallet ?
Is there a difference ? Are they the same ?

![image](https://user-images.githubusercontent.com/35063329/34517831-d8094132-f0d0-11e7-91b4-453782ae5ee3.png)

**Comment by camerk** [comment]
I am having the same issue with BTCZ wallet. has 8 connections yet stuck at 83.83% all night. Have restarted and added nodes to no avail. Mining pool has sent me money but I cannot verify BTCZ balance because wallet is stuck not syncing.

**Comment by camerk** [comment]
I solved this by moving to another computer, my laptop in this case, and downloading the wallet, running the .bat file and letting it sync. Finished in around an hour, then imported each of my private keys from my old wallet and now it reflects the balance. Desktop wallet i still bugged though.

**Comment by bitcoinz-pod** [comment]
closing
