### ISSUE TITLE
com.eclipsesource.json.ParseException

### ISSUE THREAD

**Issue by levuphuc** [bitcoinz-pod/bitcoinz-wallet#3]
I run on Windows 10 and got this message

A general unexpected critical error has occurred:
com.eclipsesource.json.ParseException: Unexpected end of input at 1:1
See the console output for more detailed error information!

![image](https://user-images.githubusercontent.com/27323713/31304447-272eb218-ab4b-11e7-9a61-09585b5271bf.png)

**Comment by bitcoinz-pod** [comment]
Please verify in latest wallet should be fine.
