### ISSUE TITLE
Empty address limit reached

### ISSUE THREAD

**Issue by compmanuk** [bitcoinz-pod/bitcoinz-wallet#37]
Hi everyone,

I'm quite new to this. I started mining BTCZ and in day 2 I started getting this error message on MyBitcoinZ wallet for mac:

"Empty addresses limit reached. New addresses cannot be generated."

My balance seems to be updating, but any input regarding this error will be much appreciated.

**Comment by bitcoinz-pod** [comment]
hey, this is windows wallet github, please reach devs @ slack in #developers channel
