### ISSUE TITLE
change blockchain directory

### ISSUE THREAD

**Issue by Zeal0usD** [bitcoinz-pod/bitcoinz-wallet#4]
There is no option to change directory, i put my BC's on a larger hard drive. This will be required at some point.

**Comment by eberlemartin** [comment]
To move all your BitcoinZ data to another location you can create a symlink on Windows (on linux aswell, but you'll have to google that yourself).
Windows:
- Move content of %userprofile%\AppData\Roaming\BitcoinZ\ to folder in new location
- Start cmd with administrator privileges
- Type: mklink /J %userprofile%\AppData\Roaming\BitcoinZ "PathToNewLocation"

Then you have all BitcoinZ Data in that new location, also your wallet data etc...but blockchain should stay quite small for some time.

Just to be safe, have a backup from your wallet before you do that ;)

**Comment by bmatthewshea** [comment]
(Feature Request)
Why not just add an installer with windows version along with an option to pick the `-datadir=`? symlink is a temp fix at best. thanks.

**Comment by skironDotNet** [comment]
The other workaround is 
1. run 
zcashd -datadir={your desireddirectory} -printtoconsole=1
2. make sure you have same copy of bitcoinz.conf in {your desired directory} and in %userprofile%\AppData\Roaming\BitcoinZ
and that rpcuser and rpcpassword is set same in both bitcoinz.conf files

3. Run UI wallet

What it does ,the GUI check config file in %userprofile%\AppData\Roaming\BitcoinZ and using rpc configuration communicates with zcashd that can be run with custom directory. The GUI is just RPC wrapper to communicate with zcashd anyway.

I hope this helps someone
