### ISSUE TITLE
Impossible to start the Wallet 

### ISSUE THREAD

**Issue by JimTriangle** [bitcoinz-pod/bitcoinz-wallet#7]
Couldn't connect to server EOF reached (code 1)
Make sure server is running and you are connecting to the correct RPC port

What do i need to do ?

i had 135 000 btcz in it...

**Comment by sluggiss** [comment]
same! disaster - wasted mining time. Any chance to recover?

**Comment by JimTriangle** [comment]
Hello sluggis.

Solution to this is here : https://bitcoinzguiding.ovh/wallet.html

You just have to go to appdata/BitcoinZ folder. Save the file wallet.dat somewhere by moving it.  Delete the content of the folder, copy back wallet.dat in the folder. Then restart the wallet and everything will be ok.

**Comment by sluggiss** [comment]
incredible! works perfectly :)))))))

THANK YOU

happy sunday!

On 3 Dec 2017, at 02:14, Jean-Marie PUJADE <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello sluggis.

Solution to this is here : https://bitcoinzguiding.ovh/wallet.html

You just have to go to appdata/BitcoinZ folder. Save the file wallet.dat somewhere by moving it. Delete the content of the folder, copy back wallet.dat in the folder. Then restart the wallet and everything will be ok.
