### ISSUE TITLE
Wallet not syncing

### ISSUE THREAD

**Issue by eksterVX** [bitcoinz-pod/bitcoinz-wallet#9]
Tried both versions of the wallet on Windows and left it running for 2h...

The program still shows blockchain synchronized: 0.02%
up to 06/11/2016

0 Network Connections.

How to fix this?

**Comment by bmatthewshea** [comment]
@eksterVX 
Consult https://github.com/bitcoinz-pod/bitcoinz/issues/1
Fixed it for me (adding active nodes)..
